### ISSUE TITLE
Move documentation from the readme into a separate folder within the project.

### ISSUE THREAD

**Issue by davelens** [udongo/udongo#21]
There really should be a way to access the docs in a readable format online.

In regards to that requirement I've tried out GitBook to see if it would be useful for us: https://www.gitbook.com/book/blimp/udongo-developer-documentation/details

Sadly they require a separate repo, which we would rather not have because we want to offer relevant docs for each release.

**Comment by bauffman** [comment]
I've messed around with splitting the docs into multiple files and this doesn't work well on github. I propose to keep everything in 1 readme file, but add docs within the concerns in the code.
